### ISSUE TITLE
Auto Update Magic JSS Frequency

### ISSUE THREAD

**Issue by mgrevtech** [homebysix/auto-update-magic#24]
So in this exercise 5c - https://github.com/homebysix/auto-update-magic#exercise-5c-configure-macs-to-check-for-updates-periodically

it is mentioned that for the Auto Update Magic policy that we create on Casper, we should set the 'Execution Frequency' to 'Once per week'. I have actually set it to 'Once per day'. But however I am kind of confused about this.
Since the script & launch daemon already gets pushed to the computers on the first run, why would we need to run this policy for a second time on the same computer? Should it not be set to 'Once per computer'? When you set it to 'Once per Day or Week' - does it not mean that the same 'autoupdate' package gets pushed over & over on the same computer? Or maybe I did not understand the workflow correctly.
Please help me understand this part.

Thanks!

**Comment by homebysix** [comment]
Hi @mgrevtech,

The reasons to deploy the script/launchdaemon pair on a recurring basis are:

- In case it fails to deploy due to DP or network issues, there's a built-in "try again later" failsafe.
- If you make changes to the script/launchdaemon, getting those changes to your fleet is as easy as replacing the existing package. The recurring policy will take care of deploying the updated version automatically.

Of course, you can simulate both of these benefits yourself if you'd prefer to simply click "Flush Logs" after updating the script/launchdaemon package, or "Flush Errors" if network issues prevent its deployment. I just wrote the instructions to be as hands-off as possible for a broad audience.

Hope that explains!
