### ISSUE TITLE
Has Casper 9.9 upset my auto-update magic?

### ISSUE THREAD

**Issue by sparkymac** [homebysix/auto-update-magic#26]
Hi

I had my setup working beautifully adding patch updates to Self Service and auto-update policies until I updated to Casper 9.9 and now I am seeing the following:

My Install Latest Packages are working and pulling the latest versions into the JSS but my Auto Update Policies still have the old version packages. I have attached some screenshots to make it clearer!

I would apreciate any help working out which recipes/ templates need changing to get this working again if it is a problem with these. If its been caused by Casper 9.9 then I guess I'll have to wait...

Thanks in advance
<img width="1305" alt="screen shot 2016-04-19 at 11 59 53" src="https://cloud.githubusercontent.com/assets/9569939/14643201/4f7edaec-0645-11e6-83c5-c0307d2c328e.png">
<img width="1313" alt="screen shot 2016-04-19 at 11 59 43" src="https://cloud.githubusercontent.com/assets/9569939/14643206/53917842-0645-11e6-990c-305c8fd3af81.png">

Mark

**Comment by homebysix** [comment]
Hi @sparkymac,

You may want to run one of your autoupdate recipes in isolation, using Terminal to see what errors occur, if any. For example: `autopkg run -v AdobeFlashPlayer-autoupdate.jss`

The policy and smart group templates associated with autoupdate recipes are conventionally called PolicyTemplate-autoupdate.xml and SmartGroupTemplate-autoupdate.xml, respectively, and they may be in your ~/Library/AutoPkg/Recipes or ~/Library/AutoPkg/RecipeOverrides folders. (Although Flash uses an EA, so you may be looking for AdobeFlashPlayerSmartGroupTemplate-autoupdate.xml instead of the regular SmartGroupTemplate.xml.)

It's possible that some of the XML used by Casper's API changed in 9.9, but it works fine on my JAMF Cloud instance (v9.91.1460045562).

**Comment by sparkymac** [comment]
Hi Elliot

Thank you for your advice which I followed with the following results:

I ran the flash autoupdate recipe using Terminal and it ran successfully and popped the latest package into the autoupdate policy.

I thought I would try Java next as that one was doing the same and only updating the non autoupdate policy. First I ran all recipes directly from the Autopkgr gui but it didn’t update the autoupdate policies as before. I then ran the autopkg run -v OracleJava8-autoupdate.jss using Terminal and it popped the latest package into the policies.

So it looks like I will need to run the recipes via Terminal to get them to work successfully unless you know a workaround!

I updated my JSS to 9.91 as well just in case but that made no difference!

I am also ready to move this from the Testing group and push to all so where do I make those changes in the recipes & smart group templates?

Thanks again.
Mark

**Comment by sparkymac** [comment]
Hi Elliot

Do you have any update on this one please?
I have just updated to 1.4.1 but it still will only run recipes with Terminal.
Also the schedules do run daily but the email notification doesn't get to me but running the 'Send Test Email' button does send an email.
All very strange!
Thanks
Mark

**Comment by homebysix** [comment]
Hi Mark,

Here are a few steps for troubleshooting:

- Rather than running the recipes individually at the Terminal, try running them from the recipe list using this command:

    ```
    /usr/bin/python /usr/local/bin/autopkg run --verbose --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt
    ````

    (Note: Change `recipe_list.txt` to the name of your recipe list, if it's something other than the default.) If that command succeeds, then you know you have working recipes and processors. That's a solid foundation to build on.

- In AutoPkgr, uncheck the __Enable scheduled AutoPkg runs__ checkbox in the __Schedule__ tab. Then check the box again. This will reload the schedule LaunchDaemon that AutoPkgr uses to initiate AutoPkg runs. You'll be prompted for your password once when you uncheck, and again when you recheck.

- Head over to the __Folders & Integration__ tab, then click on __Configure AutoPkg__. Check the box for __Verbose AutoPkg run__, then __Save and Close__.

- Click on the AutoPkgr icon in the menu bar, and make sure __Verbose Logs__ is checked.

- In the __Notifications__ tab, find the __Choose when actions trigger notification__ setting and click the __Customize__ button. Set it to __Report All Items__ (you can adjust this later, after we confirm notifications are being sent on schedule).

- Obvious, but make sure your email notification settings are correct. Sending a test email couldn't hurt.

- Remove at least one of the recipes' caches from your __~/Library/AutoPkg/Cache__ folder, so that we're guaranteed to receive a notification.

- Click the __Run Recipes Now__ button in AutoPkgr. This tests two things: (1) The same set of recipes that ran successfully in the Terminal should run successfully in AutoPkgr, and (2) you should receive notifications.

- Open up __Console.app__ and filter for `AutoPkgr`. If there are unusual errors there, paste them into this thread and I'll have a look.

Thanks!

**Comment by sparkymac** [comment]
Thanks Elliot

Everything is setup as requested and it all seems to work apart from the
auto notification email.

I wont worry too much about that , for now i will disable the schedule and
just run it manually each day, this way the email is generated.

I'm ready to change the Self service policy scope to all rather than limit
it to the testing group, what do I change to make this happen?

Thanks
Mark

**Comment by homebysix** [comment]
Closing due to repo deprecation and archival.
