### ISSUE TITLE
JSS with Sites Enabled:  Seen this issue before?

### ISSUE THREAD

**Issue by quovadimus** [homebysix/auto-update-magic#4]
I was wondering if you'd come across any issues with Sites being enabled.  Below is an error I got yesterday from AutoPkgr, but the specific error seems to be from one of the other tools.

[ERROR] Error: Computer (ID:XXX, Name:computername) is enabled for a site.

It appeared on the 2nd item, in this case Firefox.jss (GoogleChrome.jss ran first with no error).
Below is the full entry.

11/20/14 10:24:19.865 AM AutoPkgr[71342]: (FULL AUTOPKG TRACEBACK) 
File "/usr/local/bin/autopkg", line 1334, in 
sys.exit(main(sys.argv))
File "/usr/local/bin/autopkg", line 1328, in main
exit(subcommands[verb]'function')
File "/usr/local/bin/autopkg", line 1152, in run_recipes
autopackager.process(recipe)
File "/Library/AutoPkg/autopkglib/init.py", line 466, in process
self.env = processor.process()
File "/Library/AutoPkg/autopkglib/init.py", line 295, in process
self.main()
File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 596, in main
self.groups = self.handle_groups()
File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 345, in handle_groups
computer_group = self._add_or_update_smart_group(group)
File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 374, in _add_or_update_smart_group
update_env="jss_group_updated", added_env="jss_group_added")
File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 425, in _update_or_create_new
self.j.put(url, recipe_object)
File "/Library/Python/2.7/site-packages/jss/jss.py", line 238, in put
self._error_handler(JSSPutError, response)
File "/Library/Python/2.7/site-packages/jss/jss.py", line 186, in _error_handler
raise exception
jss.jss.JSSPutError: JSS Error. Response Code: 409 Response" Conflict
Error: Computer (ID:XXX, Name:computername) is enabled for a site.

I removed the computer from the site but on the second run it simply hit the error on a different machine name. I'm not actually utilizing the 'Sites' feature, it was just left over from some testing, so I removed all sites and everything went back to working normally.

**Comment by wooj1** [comment]
I ran into this today too.  Not using the site features either and removing all of the computers under my Exclusions list of the policy fixed it.

**Comment by charliwest** [comment]
I had the same issue, no exclusions though on the policy, but it was set to install on the smart group and the machine that the error quoted. Removed the policy altogether and let it run again and that resolved the issue. So looks like if you scope a policy to anything but whats in the template it freaks out, but I had this without automagic and on sheacgraigs recipe so I think its JSSImporter issue

**Comment by homebysix** [comment]
Hi @ungerjm — I don't have access to any Casper installs which use "sites," so I'm going to have to rely on others' feedback here.

Are you able to fix it by removing the policy exclusions, or by sticking to the scope defined in the policy template?

You may also want to update to the latest version of JSSImporter.

**Comment by leoos** [comment]
I know this is closed. I've just run into the same error myself. I've been testing it by going through the Auto Update Magic instructions and using the Firefox.jss. I have multiple sites in my Casper 9.32 install. Unlike Charliwest the machine causing the error dialog isn't in my firefox-update-smart group. I'm running the current AutoPkgr and the tools are all uptodate according to that.

**Comment by charliwest** [comment]
@leoos can you maybe run the recipe manually with a -vvv to get some more info on the error? Also check if the policy installing firefox is scoped to only the smart group. 
Another troubleshooting step would be to remove the policy and smart group and run the recipe again, just to see what happens maybe?

**Comment by leoos** [comment]
I've looked at this.
Removing the Policies and Smart Groups that were created in my JSS before I started adding overrides and following the instructions for AutoUpdateMagic allowed me to Check the Apps in AutoPkgr or run autopkg from the Command Line.

The problem resurfaces when I try to run the check the next time as the smart groups have been populated at this stage due to the initial run.

Below is the Traceback error message I get when I try to run my Firefox.jss a second time. This came in the terminal after the Output text I gathered in this text file. 
https://github.com/leoos/eternalfrost/blob/master/Firefox_Output
 The smartgroup is populated by the machine thats mentioned to be causing the error.

Here is the output running Adobe Flash Player with an override for the first time

https://github.com/leoos/eternalfrost/blob/master/Flash_Output

___________________________

Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 671, in main
    self.groups = self.handle_groups()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 393, in handle_groups
    computer_group = self._add_or_update_smart_group(group)
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 428, in _add_or_update_smart_group
    update_env="jss_group_updated", added_env="jss_group_added")
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 482, in _update_or_create_new
    self.j.put(url, recipe_object)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 229, in put
    self._error_handler(JSSPutError, response)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 174, in _error_handler
    raise exception
jss.exceptions.JSSPutError: JSS Error. Response Code: 409	Response" Conflict
Error: Computer (ID:573, Name:csm-test-29711) is enabled for a site.

**Comment by homebysix** [comment]
@leoos you may want to mask those passwords (and immediately change them, since GitHub's history [lives forever](https://help.github.com/articles/remove-sensitive-data/).)

**Comment by rougegoat** [comment]
I was seeing the same error.  I figured out that the fix was to add

```
<site>
     <id>id-of-site</id>
     <name>name-of-site</name>
</site>
```

to the PolicyTemplate.xml and SmartGroupTemplate.xml files in the RecipeOverrides folder.  If you're building for different sites, you may need to make multiple template files that are customized as needed.
