### ISSUE TITLE
Smart Group Idea

### ISSUE THREAD

**Issue by JonMunford** [homebysix/auto-update-magic#6]
It may be a good idea on your smart group criteria in the jss recipes to add something for not having the application at all.

Like.
If it doesn't have firefox.app
or if it has firefox.app
and the version isn't 32.x

I have added that to mine manually but it may be something to consider doing to all of the recipes you put out.

**Comment by homebysix** [comment]
I updated the SmartGroupTemplate.xml example to include "Application Version is not blank." It's not exactly what you asked for, but it can be easily adapted to do what you're wanting.

Here's an xml snippet you might want to try in order to achieve the criteria you described above:
```xml
        <criterion>
            <name>Application Title</name>
            <priority>0</priority>
            <and_or>or</and_or>
            <search_type>does not have</search_type>
            <value>%JSS_INVENTORY_NAME%</value>
        </criterion>
```
You might have to play with the `priority` and `and_or` values in order to figure out what combination produces the right logic.
